In [10]:
from mxnet import ndarray as nd

nd.zeros((3,4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [11]:
x = nd.arange(12)
x 


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [12]:
x = nd.ones((3,4))
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.array([[1,2],[2,3]])


[[1. 2.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [14]:
x.reshape((12,1))


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
<NDArray 12x1 @cpu(0)>

In [15]:
y = nd.random_normal(0,1, shape=(3,4))

In [16]:
y


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

In [17]:
y.T


[[-0.68106437  0.5712682   1.8307649 ]
 [-0.1353156  -2.7579627  -1.1468065 ]
 [ 0.37723133  1.07628     0.05383794]
 [ 0.41016456 -0.6141325  -2.5074806 ]]
<NDArray 4x3 @cpu(0)>

In [18]:
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [19]:
nd.dot(x, y.T)


[[-0.02898407 -1.7245471  -1.7696843 ]
 [-0.02898407 -1.7245471  -1.7696843 ]
 [-0.02898407 -1.7245471  -1.7696843 ]]
<NDArray 3x3 @cpu(0)>

In [20]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
print('a: ', a)
print('b: ', b)
print('a+b: ', a+b)

a:  
[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>
b:  
[[0. 1.]]
<NDArray 1x2 @cpu(0)>
a+b:  
[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>


In [21]:
x = 1+2
y = 5
bx = id(x)
x = x + y
ax = id(x)
print(bx, ax)

1523888416 1523888576


In [23]:
from mxnet import nd
from mxnet import autograd

x = nd.array([[1,2],[3,4]])
x


[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>

In [27]:
x.attach_grad()

with autograd.record():
    y = 2 * x * x

In [28]:
y.backward()
y


[[ 2.  8.]
 [18. 32.]]
<NDArray 2x2 @cpu(0)>

In [33]:
x.grad == 4*x


[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

In [31]:
y


[[ 2.  8.]
 [18. 32.]]
<NDArray 2x2 @cpu(0)>

In [34]:
def f(a):
    b = a * 2
    while nd.norm(b).asscalar() < 1000:
        b = b * 2
    if nd.sum(b).asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [38]:
a = nd.random_normal(shape=3)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [39]:
a.grad == c/a


[1. 1. 1.]
<NDArray 3 @cpu(0)>

In [42]:
a.grad


[2048. 2048. 2048.]
<NDArray 3 @cpu(0)>

In [47]:
with autograd.record():
    y = x * 2
    z = y * x
    
head_gradient = nd.array([[10,1.], [.1, .01]])
z.backward(head_gradient)
print(x.grad)


[[40.    8.  ]
 [ 1.2   0.16]]
<NDArray 2x2 @cpu(0)>


y[i] = 2 * X[i][0] - 3.4 * X[i][1] + 4.2 + noise

In [48]:
from mxnet import ndarray as nd
from mxnet import autograd

num_inputs = 2
num_examples = 1000

true_w = [2, -3.4]
true_b = 4.2

X = nd.random_normal(shape=(num_examples, num_inputs))
y = true_w[0] * X[:, 0] + true_w[1] * X[:, 1] + true_b
y += .01 * nd.random_normal(shape=y.shape)

In [49]:
print(X[0],y[0])


[1.5194443 1.9040879]
<NDArray 2 @cpu(0)> 
[0.77255136]
<NDArray 1 @cpu(0)>


In [55]:
import random
batch_size = 10
print(num_examples)
def data_iter():
    idx = list(range(num_examples))
    random.shuffle(idx)
    for i in range(0, num_examples, batch_size):
        j = nd.array(idx[i:min(i+batch_size, num_examples)])
        yield nd.take(X, j), nd.take(y, j)

1000


In [54]:
for data, label in data_iter():
    print(data, label)
    break


[[-0.94669944 -0.6836987 ]
 [-0.0842585  -0.73394597]
 [-0.9568079  -0.6704501 ]
 [ 0.99923676 -0.86133176]
 [-0.7531863   1.9670967 ]
 [-0.25803244  0.02452744]
 [-1.0347978  -0.05280134]
 [-0.37976772  0.71671826]
 [ 0.97639686 -0.38244754]
 [ 1.5864965  -1.7073821 ]]
<NDArray 10x2 @cpu(0)> 
[ 4.6507854  6.529941   4.5762944  9.121296  -3.9851577  3.6068153
  2.3093581  1.002221   7.454942  13.196527 ]
<NDArray 10 @cpu(0)>
